version: '3.8'

# Gemaakt in jaar 1 van open-ict

services:
  portfolio:
    image: php:apache
    ports:
      - "8080:80"
    volumes:
      - ${HOME}/.Portfolio:/var/www/html
    command: 
      - "/bin/bash"
      - "-c"
      - |
        a2enmod rewrite \
        && docker-php-ext-install pdo_mysql \
        && apache2-foreground
    restart: unless-stopped

  opleiding_blok_b:
    image: php:apache
    ports:
      - "8081:80"
    volumes:
      - ${HOME}/.Block_B:/var/www/html/
    command: ["/bin/bash", "-c", "a2enmod rewrite && apache2-foreground"]
    restart: unless-stopped

  opleiding_blok_c:
    image: php:apache
    ports:
      - "8082:80"
    volumes:
      - ${HOME}/.Block_C:/var/www/html/
    command: ["/bin/bash", "-c", "a2enmod rewrite && apache2-foreground"]
    restart: unless-stopped

  db:
    image: mysql:latest
    ports:  
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT_PASSWORD
      - MYSQL_USER=Portfolio
      - MYSQL_PASSWORD=PORTFOLIO_WEBSITE
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ${HOME}/.mysql:/var/lib/mysql # Mount MySQL data
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8070:80
    # Depends on db to start first
    depends_on:
      - db
    restart: unless-stopped

  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    restart: unless-stopped
    volumes:
      - ${HOME}/.Minecraft:/data

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    ports:
      - "3001:3001" 
    volumes:
      - ${HOME}/.uptime-kuma:/app/Database
    restart: always
