# Made year one of college.

version: '3.8'

services:
  portfolio:
    container_name: Portfolio
    image: php:apache
    ports:
      - "8080:80"
    volumes:
      - ../.Portfolio:/var/www/html
    command: 
      - "/bin/bash"
      - "-c"
      - |
        a2enmod rewrite \
        && docker-php-ext-install pdo_mysql \
        && apache2-foreground
    restart: unless-stopped
    depends_on:
      - mysql


  opleiding_blok_b:
    container_name: Blok_B
    image: php:apache
    ports:
      - "8081:80"
    volumes:
      - ../.Block_B:/var/www/html/
    command: 
      - "/bin/bash"
      - "-c"
      - |
        a2enmod rewrite \
        && docker-php-ext-install pdo_mysql \
        && apache2-foreground    
    restart: unless-stopped


  opleiding_blok_c:
    container_name: Blok_C
    image: php:apache
    ports:
      - "8082:80"
    volumes:
      - ../.Block_C:/var/www/html/
    command: 
      - "/bin/bash"
      - "-c"
      - |
        a2enmod rewrite \
        && docker-php-ext-install pdo_mysql \
        && apache2-foreground    
    restart: unless-stopped


  mysql:
    container_name: Database
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ../.mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: PHPMyAdmin
    image: phpmyadmin
    ports:
      - 8070:80
    depends_on:
      - mysql
    restart: unless-stopped


  minecraft:
    container_name: Minecraft
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    restart: unless-stopped
    volumes:
      - ../.Minecraft:/data

  uptime-kuma:
    container_name: kuma
    image: louislam/uptime-kuma:latest
    ports:
      - "3001:3001" 
    volumes:
      - ../.uptime-kuma:/app/Database
    restart: always
    depends_on:
      - portfolio

