version: '3.9'

services:
  # MySQL database service
  db:
    # MySQL Image used for the database
    image: mysql:8.2.0
    volumes:
      # Mounting database directory
      - ./database:/var/lib/mysql
      # Mounting SQL initialization script
      - ./Index/Database.sql:/docker-entrypoint-initdb.d/Database.sql:ro
    # Environment variables for MySQL configuration
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT_PASSWORD
      - MYSQL_USER=Portfolio_Website
      - MYSQL_PASSWORD=Damn_Boi_StrongPassword
      - MYSQL_DATABASE=Portfolio
  
  # PHPMyAdmin service
  phpmyadmin:
    # PHPMyAdmin image for managing the database
    image: phpmyadmin:5.2.1
    # Port mapping for accessing PHPMyAdmin
    ports:
      - 8080:80
    # Depends on db to start first
    depends_on:
      - db

  # Apache web server service
  apache:
    # Apache image with PHP support
    image: php:8.2.12-apache
    # Port mapping for accessing the web server
    ports:
      - 80:80
    # Mapping website content to Apache
    volumes:
      - ./Index/:/var/www/html:src
    # Depends on phpmyadmin to start first
    depends_on:
      - phpmyadmin


