services:
  portfolio:
    image: php:apache
    ports:
      - "8080:80"
    volumes:
      - "./Portfolio:/var/www/html"
    command: 
      - "/bin/bash"
      - "-c"
      - "a2enmod rewrite && docker-php-ext-install pdo_mysql && exec apache2-foreground"
    restart: unless-stopped
    depends_on:
      - mysql

  opleiding_blok_b:
    image: php:apache
    ports:
      - "8081:80"
    volumes:
      - "./.Block_B:/var/www/html"
    command: 
      - "/bin/bash"
      - "-c"
      - "a2enmod rewrite && docker-php-ext-install pdo_mysql && exec apache2-foreground"
    restart: unless-stopped

  opleiding_blok_c:
    image: php:apache
    ports:
      - "8082:80"
    volumes:
      - "./.Block_C:/var/www/html"
    command: 
      - "/bin/bash"
      - "-c"
      - "a2enmod rewrite && docker-php-ext-install pdo_mysql && exec apache2-foreground"
    restart: unless-stopped

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8070:80
    depends_on:
      - mysql
    restart: unless-stopped

  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    restart: unless-stopped
    volumes:
      - minecraft:/data

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    ports:
      - "3001:3001" 
    volumes:
      - uptime_kuma:/app/Database
    restart: always
    depends_on:
      - portfolio

volumes:
  portfolio:
  opleiding_blok_b:
  opleiding_blok_c:
  mysql:
  minecraft:
  uptime_kuma:
