version: '3.8'

services:
  portfolio:
    image: php:apache
    ports:
      - "8080:80"
    volumes:
      - ${HOME}/.Portfolio:/var/www/html
    command: ["/bin/bash", "-c", "a2enmod rewrite && apache2-foreground"]
    restart: unless-stopped

  opleiding_blok_b:
    image: php:apache
    ports:
      - "8081:80"
    volumes:
      - ${HOME}/.Block_B:/var/www/html/
    command: ["/bin/bash", "-c", "a2enmod rewrite && apache2-foreground"]
    restart: unless-stopped

  opleiding_blok_c:
    image: php:apache
    ports:
      - "8082:80"
    volumes:
      - ${HOME}/.Block_C:/var/www/html/
    command: ["/bin/bash", "-c", "a2enmod rewrite && apache2-foreground"]
    restart: unless-stopped

  db:
    image: mysql:latest
    ports:  
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=Portfolio 
      - MYSQL_USER=PHP_DOCKER
      - MYSQL_PASSWORD=<YOUR_PASSWORD>
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ${HOME}/.mysql:/var/lib/mysql # Mount MySQL data
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    restart: unless-stopped

  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    restart: unless-stopped
    volumes:
      - ${HOME}/.Minecraft:/data

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    ports:
      - "3001:3001" 
    volumes:
      - ${HOME}/.uptime-kuma:/app/Database
    restart: always
