version: '3.9'

services:
  db:
    image: mysql:8.2.0
    volumes:
      - ./database:/var/lib/mysql
      - ./databaseInitScript:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT_PASSWORD
      - MYSQL_USER=USERNAME
      - MYSQL_PASSWORD=USERPASSWORD
      - MYSQL_DATABASE=Reserveringen
    restart: always # Adding restart for the db service

  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - 8080:80
    depends_on:
      - db
    restart: always # Adding restart for the phpmyadmin service

  apache:
    build: .
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    restart: always # Adding restart for the apache service

