name: Docker Build and Push

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Docker Compose
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
          image: ubuntu:20.04
      
      - name: Build Docker images
        run: |
          docker-compose build
      
      - name: Push Docker images
        run: |
          docker-compose push
