name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change to your default branch name (e.g., 'main' or 'master')
  pull_request:
    branches:
      - main
  workflow_dispatch:      

  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: login to docker hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} || docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} || github login -u ${{ github.actor }} --with-token ${{ secrets.GITHUB_TOKEN }}

    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ github.event.repository.name }}:latest
          build-args: VERSION=${{ github.event.repository.name }}-${{ github.run_number }}