name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Change to your default branch name (e.g., 'main' or 'master')
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Generate semantic version
        id: semver
        run: |
          sleep 10
          RUN_NUMBER=${GITHUB_RUN_NUMBER}
          MAJOR=$((RUN_NUMBER / 100))
          MINOR=$(((RUN_NUMBER % 100) / 10))
          PATCH=$((RUN_NUMBER % 10))
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Calculated version: $VERSION (from run #$RUN_NUMBER)"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REPO_LC }}:latest
            ${{ env.REPO_LC }}:${{ env.VERSION }}
            ${{ env.REPO_LC }}:${{ env.VERSION }}-${{ github.sha }}
          platforms: linux/amd64,linux/arm64
