name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change to your default branch name (e.g., 'main' or 'master')
  pull_request:
    branches:
      - main
  workflow_dispatch:      

  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: first-portfolio:latest
          build-args: VERSION=${{ github.event.repository.name }}-${{ github.run_number }}